kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: spring-test-canary
spec:
  replicas: 1
  template:
    metadata:
      name: backend
      labels:
        app: spring-test
        env: canary
    spec:
      containers:
      - name: backend
        image: gcr.io/canary-spinnaker-test/spring-test
        resources:
          limits:
            memory: "500Mi"
            cpu: "100m"
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
        env:
        - name: COMPONENT
          value: backend
        - name: VERSION
          value: canary
        ports:
        - name: backend
          containerPort: 8090

