apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-test-production
  name: spring-test-production
spec:
  ports:
  - name: 8090-8090
    port: 8090
    protocol: TCP
    targetPort: 8090
  selector:
    app: spring-test
  sessionAffinity: None
  type: ClusterIP

